########################################################################################################################.
########################################################################################################################.
########                                                                                                        ########.
########      TRAINING ON WEIGHTING METHODS AND STRATEGIES  - ILO STATISTICS & ITC-ILO -  Oct/Dec 2023          ########.
########                                                                                                        ########.
########      PREPARED BY: ANTONIO R. DISCENZA - ITALIAN NATIONAL INSTITUTE OF STATISTICS - ISTAT               ########.
########                               E.mail: antonio.r.discenza@gmail.com                                     ########.
########                                                                                                        ########
########                                 CASE STUDY N. 10 - (66X_4D_ALLWR)                                      ########.
########                       CALIBRATION OF FINAL WEIGHTS USING R FOR ALL STEPS                               ########.
########                                  REUSABLE ACROSS QUARTERS AND YEARS                                    ########.
########                                                                                                        ########.
########        Version B:  Filenames, paths, reference periods and set of constraints are parameterized        ########.
########                                                                                                        ########
########       PROGRAM TO FORMAT THE SUMMARY TABLES WITH THE OUTPUT STATISTICS OF THE X VARIABLES               ########
########                                                                                                        ########.
########        4 DOMAINS  (4 Regions)                                                                          ########.
########        66 CONSTRAINTS (X1 TO X66)                                                                      ########.
########              - Population by region, sex and 12 age groups   (X1 TO X24)                               ########.
########              - Population by region, month, district and sex (X25 TO X66)                              ########.        
########                                                                                                        ########.
########                                                                                                        ########.
########################################################################################################################.
########################################################################################################################.
 
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X1"] <- "X1: ABIDJAN SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X2"] <- "X2: ABIDJAN SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X3"] <- "X3: ABIDJAN SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X4"] <- "X4: ABIDJAN SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X5"] <- "X5: HAUT-SASSANDRA SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X6"] <- "X6: HAUT-SASSANDRA SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X7"] <- "X7: HAUT-SASSANDRA SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X8"] <- "X8: HAUT-SASSANDRA SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X9"] <- "X9: PORO SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X10"] <- "X10: PORO SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X11"] <- "X11: PORO SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X12"] <- "X12: PORO SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X13"] <- "X13: GBEKE SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X14"] <- "X14: GBEKE SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X15"] <- "X15: GBEKE SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X16"] <- "X16: GBEKE SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X17"] <- "X17: INDENIE-DJUABLIN SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X18"] <- "X18: INDENIE-DJUABLIN SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X19"] <- "X19: INDENIE-DJUABLIN SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X20"] <- "X20: INDENIE-DJUABLIN SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X21"] <- "X21: TONKPI SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X22"] <- "X22: TONKPI SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X23"] <- "X23: TONKPI SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X24"] <- "X24: TONKPI SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X25"] <- "X25: YAMOUSSOUKRO SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X26"] <- "X26: YAMOUSSOUKRO SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X27"] <- "X27: YAMOUSSOUKRO SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X28"] <- "X28: YAMOUSSOUKRO SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X29"] <- "X29: GONTOUGO SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X30"] <- "X30: GONTOUGO SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X31"] <- "X31: GONTOUGO SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X32"] <- "X32: GONTOUGO SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X33"] <- "X33: SAN-PEDRO SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X34"] <- "X34: SAN-PEDRO SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X35"] <- "X35: SAN-PEDRO SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X36"] <- "X36: SAN-PEDRO SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X37"] <- "X37: KABADOUGOU SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X38"] <- "X38: KABADOUGOU SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X39"] <- "X39: KABADOUGOU SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X40"] <- "X40: KABADOUGOU SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X41"] <- "X41: N'ZI SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X42"] <- "X42: N'ZI SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X43"] <- "X43: N'ZI SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X44"] <- "X44: N'ZI SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X45"] <- "X45: MARAHOUE SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X46"] <- "X46: MARAHOUE SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X47"] <- "X47: MARAHOUE SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X48"] <- "X48: MARAHOUE SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X49"] <- "X49: SUD-COMOE SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X50"] <- "X50: SUD-COMOE SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X51"] <- "X51: SUD-COMOE SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X52"] <- "X52: SUD-COMOE SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X53"] <- "X53: WORODOUGOU SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X54"] <- "X54: WORODOUGOU SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X55"] <- "X55: WORODOUGOU SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X56"] <- "X56: WORODOUGOU SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X57"] <- "X57: LÔH-DJIBOUA SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X58"] <- "X58: LÔH-DJIBOUA SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X59"] <- "X59: LÔH-DJIBOUA SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X60"] <- "X60: LÔH-DJIBOUA SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X61"] <- "X61: AGNEBY-TIASSA SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X62"] <- "X62: AGNEBY-TIASSA SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X63"] <- "X63: AGNEBY-TIASSA SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X64"] <- "X64: AGNEBY-TIASSA SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X65"] <- "X65: GÔH SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X66"] <- "X66: GÔH SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X67"] <- "X67: GÔH SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X68"] <- "X68: GÔH SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X69"] <- "X69: CAVALLY SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X70"] <- "X70: CAVALLY SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X71"] <- "X71: CAVALLY SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X72"] <- "X72: CAVALLY SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X73"] <- "X73: BAFING SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X74"] <- "X74: BAFING SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X75"] <- "X75: BAFING SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X76"] <- "X76: BAFING SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X77"] <- "X77: BAGOUE SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X78"] <- "X78: BAGOUE SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X79"] <- "X79: BAGOUE SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X80"] <- "X80: BAGOUE SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X81"] <- "X81: BELIER SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X82"] <- "X82: BELIER SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X83"] <- "X83: BELIER SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X84"] <- "X84: BELIER SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X85"] <- "X85: BERE SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X86"] <- "X86: BERE SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X87"] <- "X87: BERE SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X88"] <- "X88: BERE SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X89"] <- "X89: BOUNKANI SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X90"] <- "X90: BOUNKANI SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X91"] <- "X91: BOUNKANI SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X92"] <- "X92: BOUNKANI SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X93"] <- "X93: FOLON SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X94"] <- "X94: FOLON SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X95"] <- "X95: FOLON SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X96"] <- "X96: FOLON SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X97"] <- "X97: GBOKLE SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X98"] <- "X98: GBOKLE SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X99"] <- "X99: GBOKLE SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X100"] <- "X100: GBOKLE SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X101"] <- "X101: GRAND-PONTS SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X102"] <- "X102: GRAND-PONTS SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X103"] <- "X103: GRAND-PONTS SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X104"] <- "X104: GRAND-PONTS SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X105"] <- "X105: GUEMON SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X106"] <- "X106: GUEMON SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X107"] <- "X107: GUEMON SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X108"] <- "X108: GUEMON SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X109"] <- "X109: HAMBOL SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X110"] <- "X110: HAMBOL SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X111"] <- "X111: HAMBOL SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X112"] <- "X112: HAMBOL SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X113"] <- "X113: IFFOU SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X114"] <- "X114: IFFOU SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X115"] <- "X115: IFFOU SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X116"] <- "X116: IFFOU SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X117"] <- "X117: LA ME SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X118"] <- "X118: LA ME SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X119"] <- "X119: LA ME SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X120"] <- "X120: LA ME SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X121"] <- "X121: NAWA SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X122"] <- "X122: NAWA SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X123"] <- "X123: NAWA SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X124"] <- "X124: NAWA SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X125"] <- "X125: TCHOLOGO SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X126"] <- "X126: TCHOLOGO SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X127"] <- "X127: TCHOLOGO SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X128"] <- "X128: TCHOLOGO SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X129"] <- "X129: MORONOU SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X130"] <- "X130: MORONOU SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X131"] <- "X131: MORONOU SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X132"] <- "X132: MORONOU SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X133"] <- "X133: NATIONAL SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X134"] <- "X134: NATIONAL SEX 1 AGE 15_19"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X135"] <- "X135: NATIONAL SEX 1 AGE 20_24"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X136"] <- "X136: NATIONAL SEX 1 AGE 25_29"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X137"] <- "X137: NATIONAL SEX 1 AGE 30_34"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X138"] <- "X138: NATIONAL SEX 1 AGE 35_39"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X139"] <- "X139: NATIONAL SEX 1 AGE 40_44"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X140"] <- "X140: NATIONAL SEX 1 AGE 45_49"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X141"] <- "X141: NATIONAL SEX 1 AGE 50_54"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X142"] <- "X142: NATIONAL SEX 1 AGE 55_59"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X143"] <- "X143: NATIONAL SEX 1 AGE 60_64"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X144"] <- "X144: NATIONAL SEX 1 AGE 65_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X145"] <- "X145: NATIONAL SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X146"] <- "X146: NATIONAL SEX 1 AGE 15_19"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X147"] <- "X147: NATIONAL SEX 1 AGE 20_24"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X148"] <- "X148: NATIONAL SEX 1 AGE 25_29"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X149"] <- "X149: NATIONAL SEX 1 AGE 30_34"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X150"] <- "X150: NATIONAL SEX 1 AGE 35_39"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X151"] <- "X151: NATIONAL SEX 1 AGE 40_44"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X152"] <- "X152: NATIONAL SEX 1 AGE 45_49"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X153"] <- "X153: NATIONAL SEX 1 AGE 50_54"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X154"] <- "X154: NATIONAL SEX 1 AGE 55_59"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X155"] <- "X155: NATIONAL SEX 1 AGE 60_64"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X156"] <- "X156: NATIONAL SEX 1 AGE 65_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X157"] <- "X157: NATIONAL SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X158"] <- "X158: NATIONAL SEX 2 AGE 15_19"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X159"] <- "X159: NATIONAL SEX 2 AGE 20_24"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X160"] <- "X160: NATIONAL SEX 2 AGE 25_29"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X161"] <- "X161: NATIONAL SEX 2 AGE 30_34"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X162"] <- "X162: NATIONAL SEX 2 AGE 35_39"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X163"] <- "X163: NATIONAL SEX 2 AGE 40_44"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X164"] <- "X164: NATIONAL SEX 2 AGE 45_49"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X165"] <- "X165: NATIONAL SEX 2 AGE 50_54"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X166"] <- "X166: NATIONAL SEX 2 AGE 55_59"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X167"] <- "X167: NATIONAL SEX 2 AGE 60_64"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X168"] <- "X168: NATIONAL SEX 2 AGE 65_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X169"] <- "X169: NATIONAL SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X170"] <- "X170: NATIONAL SEX 2 AGE 15_19"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X171"] <- "X171: NATIONAL SEX 2 AGE 20_24"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X172"] <- "X172: NATIONAL SEX 2 AGE 25_29"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X173"] <- "X173: NATIONAL SEX 2 AGE 30_34"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X174"] <- "X174: NATIONAL SEX 2 AGE 35_39"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X175"] <- "X175: NATIONAL SEX 2 AGE 40_44"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X176"] <- "X176: NATIONAL SEX 2 AGE 45_49"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X177"] <- "X177: NATIONAL SEX 2 AGE 50_54"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X178"] <- "X178: NATIONAL SEX 2 AGE 55_59"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X179"] <- "X179: NATIONAL SEX 2 AGE 60_64"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X180"] <- "X180: NATIONAL SEX 2 AGE 65_plus"
