tmpKT$X1[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe == 1  & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "0_14"& tmpKT$Sexe == 1  & tmpKT$Milieu == 1 ]
tmpKT$X2[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "15_19" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "15_19"& tmpKT$Sexe == 1  & tmpKT$Milieu == 1 ]
tmpKT$X3[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "20_24" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "20_24"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X4[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "25_29" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "25_29"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X5[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "30_34" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "30_34"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X6[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "35_39" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "35_39"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X7[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "40_44" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "40_44"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X8[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "45_49" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "45_49"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X9[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "50_54" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "50_54"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X10[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "55_59" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "55_59"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X11[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "60_64" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "60_64"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X12[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "65_plus" & tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "65_plus"& tmpKT$Sexe == 1 & tmpKT$Milieu == 1 ]
tmpKT$X13[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "0_14"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X14[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "15_19" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "15_19"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X15[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "20_24" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "20_24"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X16[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "25_29" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "25_29"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X17[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "30_34" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "30_34"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X18[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "35_39" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "35_39"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X19[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "40_44" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "40_44"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X20[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "45_49" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "45_49"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X21[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "50_54" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "50_54"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X22[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "55_59" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "55_59"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X23[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "60_64" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "60_64"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X24[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "65_plus" & tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "65_plus"& tmpKT$Sexe == 1 & tmpKT$Milieu == 2 ]
tmpKT$X25[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe == 2  & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "0_14"& tmpKT$Sexe == 2  & tmpKT$Milieu == 1 ]
tmpKT$X26[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "15_19" & tmpKT$Sexe == 2  & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "15_19"& tmpKT$Sexe == 2  & tmpKT$Milieu == 1 ]
tmpKT$X27[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "20_24" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "20_24"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X28[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "25_29" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "25_29"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X29[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "30_34" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "30_34"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X30[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "35_39" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "35_39"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X31[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "40_44" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "40_44"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X32[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "45_49" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "45_49"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X33[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "50_54" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "50_54"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X34[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "55_59" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "55_59"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X35[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "60_64" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "60_64"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X36[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "65_plus" & tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "65_plus"& tmpKT$Sexe == 2 & tmpKT$Milieu == 1 ]
tmpKT$X37[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "0_14"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X38[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "15_19" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "15_19"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X39[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "20_24" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "20_24"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X40[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "25_29" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "25_29"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X41[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "30_34" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "30_34"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X42[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "35_39" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "35_39"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X43[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "40_44" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "40_44"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X44[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "45_49" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "45_49"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X45[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "50_54" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "50_54"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X46[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "55_59" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "55_59"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X47[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "60_64" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "60_64"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]
tmpKT$X48[ tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "65_plus" & tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ] = tmpKT$Nombre[tmpKT$`Région (33)` == "NATIONAL" & tmpKT$groupe_age == "65_plus"& tmpKT$Sexe == 2 & tmpKT$Milieu == 2 ]



tmpKT$X49[tmpKT$`Région (33)` == "ABIDJAN" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "ABIDJAN" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X50[tmpKT$`Région (33)` == "ABIDJAN" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "ABIDJAN" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X51[tmpKT$`Région (33)` == "ABIDJAN" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "ABIDJAN" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X52[tmpKT$`Région (33)` == "ABIDJAN" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "ABIDJAN" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X53[tmpKT$`Région (33)` == "HAUT-SASSANDRA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "HAUT-SASSANDRA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X54[tmpKT$`Région (33)` == "HAUT-SASSANDRA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "HAUT-SASSANDRA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X55[tmpKT$`Région (33)` == "HAUT-SASSANDRA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "HAUT-SASSANDRA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X56[tmpKT$`Région (33)` == "HAUT-SASSANDRA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "HAUT-SASSANDRA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X57[tmpKT$`Région (33)` == "PORO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "PORO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X58[tmpKT$`Région (33)` == "PORO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "PORO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X59[tmpKT$`Région (33)` == "PORO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "PORO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X60[tmpKT$`Région (33)` == "PORO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "PORO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X61[tmpKT$`Région (33)` == "GBEKE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GBEKE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X62[tmpKT$`Région (33)` == "GBEKE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GBEKE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X63[tmpKT$`Région (33)` == "GBEKE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GBEKE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X64[tmpKT$`Région (33)` == "GBEKE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GBEKE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X65[tmpKT$`Région (33)` == "INDENIE-DJUABLIN" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "INDENIE-DJUABLIN" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X66[tmpKT$`Région (33)` == "INDENIE-DJUABLIN" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "INDENIE-DJUABLIN" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X67[tmpKT$`Région (33)` == "INDENIE-DJUABLIN" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "INDENIE-DJUABLIN" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X68[tmpKT$`Région (33)` == "INDENIE-DJUABLIN" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "INDENIE-DJUABLIN" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X69[tmpKT$`Région (33)` == "TONKPI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "TONKPI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X70[tmpKT$`Région (33)` == "TONKPI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "TONKPI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X71[tmpKT$`Région (33)` == "TONKPI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "TONKPI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X72[tmpKT$`Région (33)` == "TONKPI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "TONKPI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X73[tmpKT$`Région (33)` == "YAMOUSSOUKRO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "YAMOUSSOUKRO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X74[tmpKT$`Région (33)` == "YAMOUSSOUKRO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "YAMOUSSOUKRO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X75[tmpKT$`Région (33)` == "YAMOUSSOUKRO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "YAMOUSSOUKRO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X76[tmpKT$`Région (33)` == "YAMOUSSOUKRO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "YAMOUSSOUKRO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X77[tmpKT$`Région (33)` == "GONTOUGO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GONTOUGO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X78[tmpKT$`Région (33)` == "GONTOUGO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GONTOUGO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X79[tmpKT$`Région (33)` == "GONTOUGO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GONTOUGO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X80[tmpKT$`Région (33)` == "GONTOUGO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GONTOUGO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X81[tmpKT$`Région (33)` == "SAN-PEDRO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "SAN-PEDRO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X82[tmpKT$`Région (33)` == "SAN-PEDRO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "SAN-PEDRO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X83[tmpKT$`Région (33)` == "SAN-PEDRO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "SAN-PEDRO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X84[tmpKT$`Région (33)` == "SAN-PEDRO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "SAN-PEDRO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X85[tmpKT$`Région (33)` == "KABADOUGOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "KABADOUGOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X86[tmpKT$`Région (33)` == "KABADOUGOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "KABADOUGOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X87[tmpKT$`Région (33)` == "KABADOUGOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "KABADOUGOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X88[tmpKT$`Région (33)` == "KABADOUGOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "KABADOUGOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X89[tmpKT$`Région (33)` == "N'ZI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "N'ZI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X90[tmpKT$`Région (33)` == "N'ZI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "N'ZI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X91[tmpKT$`Région (33)` == "N'ZI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "N'ZI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X92[tmpKT$`Région (33)` == "N'ZI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "N'ZI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X93[tmpKT$`Région (33)` == "MARAHOUE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "MARAHOUE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X94[tmpKT$`Région (33)` == "MARAHOUE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "MARAHOUE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X95[tmpKT$`Région (33)` == "MARAHOUE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "MARAHOUE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X96[tmpKT$`Région (33)` == "MARAHOUE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "MARAHOUE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X97[tmpKT$`Région (33)` == "SUD-COMOE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "SUD-COMOE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X98[tmpKT$`Région (33)` == "SUD-COMOE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "SUD-COMOE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X99[tmpKT$`Région (33)` == "SUD-COMOE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "SUD-COMOE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X100[tmpKT$`Région (33)` == "SUD-COMOE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "SUD-COMOE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X101[tmpKT$`Région (33)` == "WORODOUGOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "WORODOUGOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X102[tmpKT$`Région (33)` == "WORODOUGOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "WORODOUGOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X103[tmpKT$`Région (33)` == "WORODOUGOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "WORODOUGOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X104[tmpKT$`Région (33)` == "WORODOUGOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "WORODOUGOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X105[tmpKT$`Région (33)` == "LÔH-DJIBOUA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "LÔH-DJIBOUA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X106[tmpKT$`Région (33)` == "LÔH-DJIBOUA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "LÔH-DJIBOUA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X107[tmpKT$`Région (33)` == "LÔH-DJIBOUA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "LÔH-DJIBOUA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X108[tmpKT$`Région (33)` == "LÔH-DJIBOUA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "LÔH-DJIBOUA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X109[tmpKT$`Région (33)` == "AGNEBY-TIASSA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "AGNEBY-TIASSA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X110[tmpKT$`Région (33)` == "AGNEBY-TIASSA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "AGNEBY-TIASSA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X111[tmpKT$`Région (33)` == "AGNEBY-TIASSA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "AGNEBY-TIASSA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X112[tmpKT$`Région (33)` == "AGNEBY-TIASSA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "AGNEBY-TIASSA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X113[tmpKT$`Région (33)` == "GÔH" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GÔH" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X114[tmpKT$`Région (33)` == "GÔH" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GÔH" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X115[tmpKT$`Région (33)` == "GÔH" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GÔH" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X116[tmpKT$`Région (33)` == "GÔH" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GÔH" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X117[tmpKT$`Région (33)` == "CAVALLY" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "CAVALLY" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X118[tmpKT$`Région (33)` == "CAVALLY" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "CAVALLY" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X119[tmpKT$`Région (33)` == "CAVALLY" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "CAVALLY" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X120[tmpKT$`Région (33)` == "CAVALLY" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "CAVALLY" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X121[tmpKT$`Région (33)` == "BAFING" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BAFING" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X122[tmpKT$`Région (33)` == "BAFING" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BAFING" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X123[tmpKT$`Région (33)` == "BAFING" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BAFING" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X124[tmpKT$`Région (33)` == "BAFING" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BAFING" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X125[tmpKT$`Région (33)` == "BAGOUE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BAGOUE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X126[tmpKT$`Région (33)` == "BAGOUE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BAGOUE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X127[tmpKT$`Région (33)` == "BAGOUE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BAGOUE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X128[tmpKT$`Région (33)` == "BAGOUE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BAGOUE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X129[tmpKT$`Région (33)` == "BELIER" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BELIER" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X130[tmpKT$`Région (33)` == "BELIER" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BELIER" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X131[tmpKT$`Région (33)` == "BELIER" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BELIER" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X132[tmpKT$`Région (33)` == "BELIER" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BELIER" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X133[tmpKT$`Région (33)` == "BERE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BERE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X134[tmpKT$`Région (33)` == "BERE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BERE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X135[tmpKT$`Région (33)` == "BERE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BERE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X136[tmpKT$`Région (33)` == "BERE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BERE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X137[tmpKT$`Région (33)` == "BOUNKANI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BOUNKANI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X138[tmpKT$`Région (33)` == "BOUNKANI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BOUNKANI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X139[tmpKT$`Région (33)` == "BOUNKANI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BOUNKANI" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X140[tmpKT$`Région (33)` == "BOUNKANI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "BOUNKANI" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X141[tmpKT$`Région (33)` == "FOLON" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "FOLON" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X142[tmpKT$`Région (33)` == "FOLON" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "FOLON" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X143[tmpKT$`Région (33)` == "FOLON" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "FOLON" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X144[tmpKT$`Région (33)` == "FOLON" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "FOLON" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X145[tmpKT$`Région (33)` == "GBOKLE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GBOKLE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X146[tmpKT$`Région (33)` == "GBOKLE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GBOKLE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X147[tmpKT$`Région (33)` == "GBOKLE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GBOKLE" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X148[tmpKT$`Région (33)` == "GBOKLE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GBOKLE" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X149[tmpKT$`Région (33)` == "GRAND-PONTS" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GRAND-PONTS" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X150[tmpKT$`Région (33)` == "GRAND-PONTS" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GRAND-PONTS" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X151[tmpKT$`Région (33)` == "GRAND-PONTS" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GRAND-PONTS" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X152[tmpKT$`Région (33)` == "GRAND-PONTS" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GRAND-PONTS" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X153[tmpKT$`Région (33)` == "GUEMON" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GUEMON" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X154[tmpKT$`Région (33)` == "GUEMON" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GUEMON" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X155[tmpKT$`Région (33)` == "GUEMON" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GUEMON" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X156[tmpKT$`Région (33)` == "GUEMON" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "GUEMON" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X157[tmpKT$`Région (33)` == "HAMBOL" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "HAMBOL" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X158[tmpKT$`Région (33)` == "HAMBOL" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "HAMBOL" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X159[tmpKT$`Région (33)` == "HAMBOL" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "HAMBOL" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X160[tmpKT$`Région (33)` == "HAMBOL" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "HAMBOL" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X161[tmpKT$`Région (33)` == "IFFOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "IFFOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X162[tmpKT$`Région (33)` == "IFFOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "IFFOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X163[tmpKT$`Région (33)` == "IFFOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "IFFOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X164[tmpKT$`Région (33)` == "IFFOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "IFFOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X165[tmpKT$`Région (33)` == "LA ME" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "LA ME" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X166[tmpKT$`Région (33)` == "LA ME" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "LA ME" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X167[tmpKT$`Région (33)` == "LA ME" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "LA ME" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X168[tmpKT$`Région (33)` == "LA ME" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "LA ME" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X169[tmpKT$`Région (33)` == "NAWA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "NAWA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X170[tmpKT$`Région (33)` == "NAWA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "NAWA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X171[tmpKT$`Région (33)` == "NAWA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "NAWA" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X172[tmpKT$`Région (33)` == "NAWA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "NAWA" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X173[tmpKT$`Région (33)` == "TCHOLOGO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "TCHOLOGO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X174[tmpKT$`Région (33)` == "TCHOLOGO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "TCHOLOGO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X175[tmpKT$`Région (33)` == "TCHOLOGO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "TCHOLOGO" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X176[tmpKT$`Région (33)` == "TCHOLOGO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "TCHOLOGO" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
tmpKT$X177[tmpKT$`Région (33)` == "MORONOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "MORONOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==1]
tmpKT$X178[tmpKT$`Région (33)` == "MORONOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1] = tmpKT$Nombre[ tmpKT$`Région (33)` == "MORONOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==1]
tmpKT$X179[tmpKT$`Région (33)` == "MORONOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "MORONOU" & tmpKT$groupe_age == "0_14" & tmpKT$Sexe ==2]
tmpKT$X180[tmpKT$`Région (33)` == "MORONOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2] = tmpKT$Nombre[ tmpKT$`Région (33)` == "MORONOU" & tmpKT$groupe_age == "15_plus" & tmpKT$Sexe ==2]
