replace District="AUTONOME D'ABIDJAN" if reg =="ABIDJAN"
replace District="AUTONOME DE YAMOUSSOUKRO" if reg =="YAMOUSSOUKRO"
replace District="BAS-SASSANDRA" if reg =="SAN-PEDRO"
replace District="BAS-SASSANDRA" if reg =="GBOKLE"
replace District="BAS-SASSANDRA" if reg =="NAWA"
replace District="COMOE" if reg =="INDENIE-DJUABLIN"
replace District="COMOE" if reg =="SUD-COMOE"
replace District="DENGUELE" if reg =="KABADOUGOU"
replace District="DENGUELE" if reg =="FOLON"
replace District="GOH-DJIBOUA" if reg =="LÔH-DJIBOUA"
replace District="GOH-DJIBOUA" if reg =="GÔH"
replace District="HAUT-SASSANDRA-MARAHOUE" if reg =="HAUT-SASSANDRA"
replace District="HAUT-SASSANDRA-MARAHOUE" if reg =="MARAHOUE"
replace District="LACS" if reg =="N'ZI"
replace District="LACS" if reg =="BELIER"
replace District="LACS" if reg =="IFFOU"
replace District="LACS" if reg =="MORONOU"
replace District="LAGUNES" if reg =="AGNEBY-TIASSA"
replace District="LAGUNES" if reg =="GRAND-PONTS"
replace District="LAGUNES" if reg =="LA ME"
replace District="MONTAGNES" if reg =="TONKPI"
replace District="MONTAGNES" if reg =="CAVALLY"
replace District="MONTAGNES" if reg =="GUEMON"
replace District="SAVANES" if reg =="PORO"
replace District="SAVANES" if reg =="BAGOUE"
replace District="SAVANES" if reg =="TCHOLOGO"
replace District="VALLEE DU BANDAMA" if reg =="GBEKE"
replace District="VALLEE DU BANDAMA" if reg =="HAMBOL"
replace District="WOROBA" if reg =="WORODOUGOU"
replace District="WOROBA" if reg =="BAFING"
replace District="WOROBA" if reg =="BERE"
replace District="ZANZAN" if reg =="GONTOUGO"
replace District="ZANZAN" if reg =="BOUNKANI"
