########################################################################################################################.
########################################################################################################################.
########                                                                                                        ########.
########      TRAINING ON WEIGHTING METHODS AND STRATEGIES  - ILO STATISTICS & ITC-ILO -  Oct/Dec 2023          ########.
########                                                                                                        ########.
########      PREPARED BY: ANTONIO R. DISCENZA - ITALIAN NATIONAL INSTITUTE OF STATISTICS - ISTAT               ########.
########                               E.mail: antonio.r.discenza@gmail.com                                     ########.
########                                                                                                        ########
########                                 CASE STUDY N. 10 - (66X_4D_ALLWR)                                      ########.
########                       CALIBRATION OF FINAL WEIGHTS USING R FOR ALL STEPS                               ########.
########                                  REUSABLE ACROSS QUARTERS AND YEARS                                    ########.
########                                                                                                        ########.
########        Version B:  Filenames, paths, reference periods and set of constraints are parameterized        ########.
########                                                                                                        ########
########       PROGRAM TO FORMAT THE SUMMARY TABLES WITH THE OUTPUT STATISTICS OF THE X VARIABLES               ########
########                                                                                                        ########.
########        4 DOMAINS  (4 Regions)                                                                          ########.
########        66 CONSTRAINTS (X1 TO X66)                                                                      ########.
########              - Population by region, sex and 12 age groups   (X1 TO X24)                               ########.
########              - Population by region, month, district and sex (X25 TO X66)                              ########.        
########                                                                                                        ########.
########                                                                                                        ########.
########################################################################################################################.
########################################################################################################################.
 
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X1"] <- "X1: NATIONAL MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X2"] <- "X2: NATIONAL MILIEU 1 SEX 1 AGE 15_19"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X3"] <- "X3: NATIONAL MILIEU 1 SEX 1 AGE 20_24"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X4"] <- "X4: NATIONAL MILIEU 1 SEX 1 AGE 25_29"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X5"] <- "X5: NATIONAL MILIEU 1 SEX 1 AGE 30_34"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X6"] <- "X6: NATIONAL MILIEU 1 SEX 1 AGE 35_39"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X7"] <- "X7: NATIONAL MILIEU 1 SEX 1 AGE 40_44"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X8"] <- "X8: NATIONAL MILIEU 1 SEX 1 AGE 45_49"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X9"] <- "X9: NATIONAL MILIEU 1 SEX 1 AGE 50_54"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X10"] <- "X10: NATIONAL MILIEU 1 SEX 1 AGE 55_59"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X11"] <- "X11: NATIONAL MILIEU 1 SEX 1 AGE 60_64"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X12"] <- "X12: NATIONAL MILIEU 1 SEX 1 AGE 65_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X13"] <- "X13: NATIONAL MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X14"] <- "X14: NATIONAL MILIEU 2 SEX 1 AGE 15_19"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X15"] <- "X15: NATIONAL MILIEU 2 SEX 1 AGE 20_24"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X16"] <- "X16: NATIONAL MILIEU 2 SEX 1 AGE 25_29"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X17"] <- "X17: NATIONAL MILIEU 2 SEX 1 AGE 30_34"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X18"] <- "X18: NATIONAL MILIEU 2 SEX 1 AGE 35_39"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X19"] <- "X19: NATIONAL MILIEU 2 SEX 1 AGE 40_44"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X20"] <- "X20: NATIONAL MILIEU 2 SEX 1 AGE 45_49"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X21"] <- "X21: NATIONAL MILIEU 2 SEX 1 AGE 50_54"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X22"] <- "X22: NATIONAL MILIEU 2 SEX 1 AGE 55_59"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X23"] <- "X23: NATIONAL MILIEU 2 SEX 1 AGE 60_64"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X24"] <- "X24: NATIONAL MILIEU 2 SEX 1 AGE 65_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X25"] <- "X25: NATIONAL MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X26"] <- "X26: NATIONAL MILIEU 1 SEX 2 AGE 15_19"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X27"] <- "X27: NATIONAL MILIEU 1 SEX 2 AGE 20_24"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X28"] <- "X28: NATIONAL MILIEU 1 SEX 2 AGE 25_29"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X29"] <- "X29: NATIONAL MILIEU 1 SEX 2 AGE 30_34"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X30"] <- "X30: NATIONAL MILIEU 1 SEX 2 AGE 35_39"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X31"] <- "X31: NATIONAL MILIEU 1 SEX 2 AGE 40_44"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X32"] <- "X32: NATIONAL MILIEU 1 SEX 2 AGE 45_49"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X33"] <- "X33: NATIONAL MILIEU 1 SEX 2 AGE 50_54"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X34"] <- "X34: NATIONAL MILIEU 1 SEX 2 AGE 55_59"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X35"] <- "X35: NATIONAL MILIEU 1 SEX 2 AGE 60_64"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X36"] <- "X36: NATIONAL MILIEU 1 SEX 2 AGE 65_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X37"] <- "X37: NATIONAL MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X38"] <- "X38: NATIONAL MILIEU 2 SEX 2 AGE 15_19"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X39"] <- "X39: NATIONAL MILIEU 2 SEX 2 AGE 20_24"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X40"] <- "X40: NATIONAL MILIEU 2 SEX 2 AGE 25_29"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X41"] <- "X41: NATIONAL MILIEU 2 SEX 2 AGE 30_34"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X42"] <- "X42: NATIONAL MILIEU 2 SEX 2 AGE 35_39"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X43"] <- "X43: NATIONAL MILIEU 2 SEX 2 AGE 40_44"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X44"] <- "X44: NATIONAL MILIEU 2 SEX 2 AGE 45_49"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X45"] <- "X45: NATIONAL MILIEU 2 SEX 2 AGE 50_54"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X46"] <- "X46: NATIONAL MILIEU 2 SEX 2 AGE 55_59"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X47"] <- "X47: NATIONAL MILIEU 2 SEX 2 AGE 60_64"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X48"] <- "X48: NATIONAL MILIEU 2 SEX 2 AGE 65_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X49"] <- "X49: ABIDJAN MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X50"] <- "X50: ABIDJAN MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X51"] <- "X51: ABIDJAN MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X52"] <- "X52: ABIDJAN MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X53"] <- "X53: ABIDJAN MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X54"] <- "X54: ABIDJAN MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X55"] <- "X55: ABIDJAN MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X56"] <- "X56: ABIDJAN MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X57"] <- "X57: HAUT-SASSANDRA MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X58"] <- "X58: HAUT-SASSANDRA MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X59"] <- "X59: HAUT-SASSANDRA MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X60"] <- "X60: HAUT-SASSANDRA MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X61"] <- "X61: HAUT-SASSANDRA MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X62"] <- "X62: HAUT-SASSANDRA MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X63"] <- "X63: HAUT-SASSANDRA MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X64"] <- "X64: HAUT-SASSANDRA MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X65"] <- "X65: PORO MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X66"] <- "X66: PORO MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X67"] <- "X67: PORO MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X68"] <- "X68: PORO MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X69"] <- "X69: PORO MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X70"] <- "X70: PORO MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X71"] <- "X71: PORO MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X72"] <- "X72: PORO MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X73"] <- "X73: GBEKE MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X74"] <- "X74: GBEKE MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X75"] <- "X75: GBEKE MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X76"] <- "X76: GBEKE MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X77"] <- "X77: GBEKE MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X78"] <- "X78: GBEKE MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X79"] <- "X79: GBEKE MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X80"] <- "X80: GBEKE MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X81"] <- "X81: INDENIE-DJUABLIN MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X82"] <- "X82: INDENIE-DJUABLIN MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X83"] <- "X83: INDENIE-DJUABLIN MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X84"] <- "X84: INDENIE-DJUABLIN MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X85"] <- "X85: INDENIE-DJUABLIN MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X86"] <- "X86: INDENIE-DJUABLIN MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X87"] <- "X87: INDENIE-DJUABLIN MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X88"] <- "X88: INDENIE-DJUABLIN MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X89"] <- "X89: TONKPI MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X90"] <- "X90: TONKPI MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X91"] <- "X91: TONKPI MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X92"] <- "X92: TONKPI MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X93"] <- "X93: TONKPI MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X94"] <- "X94: TONKPI MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X95"] <- "X95: TONKPI MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X96"] <- "X96: TONKPI MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X97"] <- "X97: YAMOUSSOUKRO MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X98"] <- "X98: YAMOUSSOUKRO MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X99"] <- "X99: YAMOUSSOUKRO MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X100"] <- "X100: YAMOUSSOUKRO MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X101"] <- "X101: YAMOUSSOUKRO MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X102"] <- "X102: YAMOUSSOUKRO MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X103"] <- "X103: YAMOUSSOUKRO MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X104"] <- "X104: YAMOUSSOUKRO MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X105"] <- "X105: GONTOUGO MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X106"] <- "X106: GONTOUGO MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X107"] <- "X107: GONTOUGO MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X108"] <- "X108: GONTOUGO MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X109"] <- "X109: GONTOUGO MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X110"] <- "X110: GONTOUGO MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X111"] <- "X111: GONTOUGO MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X112"] <- "X112: GONTOUGO MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X113"] <- "X113: SAN-PEDRO MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X114"] <- "X114: SAN-PEDRO MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X115"] <- "X115: SAN-PEDRO MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X116"] <- "X116: SAN-PEDRO MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X117"] <- "X117: SAN-PEDRO MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X118"] <- "X118: SAN-PEDRO MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X119"] <- "X119: SAN-PEDRO MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X120"] <- "X120: SAN-PEDRO MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X121"] <- "X121: KABADOUGOU MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X122"] <- "X122: KABADOUGOU MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X123"] <- "X123: KABADOUGOU MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X124"] <- "X124: KABADOUGOU MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X125"] <- "X125: KABADOUGOU MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X126"] <- "X126: KABADOUGOU MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X127"] <- "X127: KABADOUGOU MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X128"] <- "X128: KABADOUGOU MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X129"] <- "X129: N'ZI MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X130"] <- "X130: N'ZI MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X131"] <- "X131: N'ZI MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X132"] <- "X132: N'ZI MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X133"] <- "X133: N'ZI MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X134"] <- "X134: N'ZI MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X135"] <- "X135: N'ZI MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X136"] <- "X136: N'ZI MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X137"] <- "X137: MARAHOUE MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X138"] <- "X138: MARAHOUE MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X139"] <- "X139: MARAHOUE MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X140"] <- "X140: MARAHOUE MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X141"] <- "X141: MARAHOUE MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X142"] <- "X142: MARAHOUE MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X143"] <- "X143: MARAHOUE MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X144"] <- "X144: MARAHOUE MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X145"] <- "X145: SUD-COMOE MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X146"] <- "X146: SUD-COMOE MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X147"] <- "X147: SUD-COMOE MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X148"] <- "X148: SUD-COMOE MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X149"] <- "X149: SUD-COMOE MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X150"] <- "X150: SUD-COMOE MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X151"] <- "X151: SUD-COMOE MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X152"] <- "X152: SUD-COMOE MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X153"] <- "X153: WORODOUGOU MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X154"] <- "X154: WORODOUGOU MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X155"] <- "X155: WORODOUGOU MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X156"] <- "X156: WORODOUGOU MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X157"] <- "X157: WORODOUGOU MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X158"] <- "X158: WORODOUGOU MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X159"] <- "X159: WORODOUGOU MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X160"] <- "X160: WORODOUGOU MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X161"] <- "X161: LÔH-DJIBOUA MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X162"] <- "X162: LÔH-DJIBOUA MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X163"] <- "X163: LÔH-DJIBOUA MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X164"] <- "X164: LÔH-DJIBOUA MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X165"] <- "X165: LÔH-DJIBOUA MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X166"] <- "X166: LÔH-DJIBOUA MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X167"] <- "X167: LÔH-DJIBOUA MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X168"] <- "X168: LÔH-DJIBOUA MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X169"] <- "X169: AGNEBY-TIASSA MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X170"] <- "X170: AGNEBY-TIASSA MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X171"] <- "X171: AGNEBY-TIASSA MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X172"] <- "X172: AGNEBY-TIASSA MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X173"] <- "X173: AGNEBY-TIASSA MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X174"] <- "X174: AGNEBY-TIASSA MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X175"] <- "X175: AGNEBY-TIASSA MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X176"] <- "X176: AGNEBY-TIASSA MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X177"] <- "X177: GÔH MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X178"] <- "X178: GÔH MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X179"] <- "X179: GÔH MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X180"] <- "X180: GÔH MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X181"] <- "X181: GÔH MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X182"] <- "X182: GÔH MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X183"] <- "X183: GÔH MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X184"] <- "X184: GÔH MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X185"] <- "X185: CAVALLY MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X186"] <- "X186: CAVALLY MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X187"] <- "X187: CAVALLY MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X188"] <- "X188: CAVALLY MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X189"] <- "X189: CAVALLY MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X190"] <- "X190: CAVALLY MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X191"] <- "X191: CAVALLY MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X192"] <- "X192: CAVALLY MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X193"] <- "X193: BAFING MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X194"] <- "X194: BAFING MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X195"] <- "X195: BAFING MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X196"] <- "X196: BAFING MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X197"] <- "X197: BAFING MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X198"] <- "X198: BAFING MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X199"] <- "X199: BAFING MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X200"] <- "X200: BAFING MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X201"] <- "X201: BAGOUE MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X202"] <- "X202: BAGOUE MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X203"] <- "X203: BAGOUE MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X204"] <- "X204: BAGOUE MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X205"] <- "X205: BAGOUE MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X206"] <- "X206: BAGOUE MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X207"] <- "X207: BAGOUE MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X208"] <- "X208: BAGOUE MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X209"] <- "X209: BELIER MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X210"] <- "X210: BELIER MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X211"] <- "X211: BELIER MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X212"] <- "X212: BELIER MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X213"] <- "X213: BELIER MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X214"] <- "X214: BELIER MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X215"] <- "X215: BELIER MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X216"] <- "X216: BELIER MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X217"] <- "X217: BERE MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X218"] <- "X218: BERE MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X219"] <- "X219: BERE MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X220"] <- "X220: BERE MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X221"] <- "X221: BERE MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X222"] <- "X222: BERE MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X223"] <- "X223: BERE MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X224"] <- "X224: BERE MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X225"] <- "X225: BOUNKANI MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X226"] <- "X226: BOUNKANI MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X227"] <- "X227: BOUNKANI MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X228"] <- "X228: BOUNKANI MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X229"] <- "X229: BOUNKANI MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X230"] <- "X230: BOUNKANI MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X231"] <- "X231: BOUNKANI MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X232"] <- "X232: BOUNKANI MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X233"] <- "X233: FOLON MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X234"] <- "X234: FOLON MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X235"] <- "X235: FOLON MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X236"] <- "X236: FOLON MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X237"] <- "X237: FOLON MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X238"] <- "X238: FOLON MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X239"] <- "X239: FOLON MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X240"] <- "X240: FOLON MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X241"] <- "X241: GBOKLE MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X242"] <- "X242: GBOKLE MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X243"] <- "X243: GBOKLE MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X244"] <- "X244: GBOKLE MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X245"] <- "X245: GBOKLE MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X246"] <- "X246: GBOKLE MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X247"] <- "X247: GBOKLE MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X248"] <- "X248: GBOKLE MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X249"] <- "X249: GRAND-PONTS MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X250"] <- "X250: GRAND-PONTS MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X251"] <- "X251: GRAND-PONTS MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X252"] <- "X252: GRAND-PONTS MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X253"] <- "X253: GRAND-PONTS MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X254"] <- "X254: GRAND-PONTS MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X255"] <- "X255: GRAND-PONTS MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X256"] <- "X256: GRAND-PONTS MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X257"] <- "X257: GUEMON MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X258"] <- "X258: GUEMON MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X259"] <- "X259: GUEMON MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X260"] <- "X260: GUEMON MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X261"] <- "X261: GUEMON MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X262"] <- "X262: GUEMON MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X263"] <- "X263: GUEMON MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X264"] <- "X264: GUEMON MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X265"] <- "X265: HAMBOL MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X266"] <- "X266: HAMBOL MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X267"] <- "X267: HAMBOL MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X268"] <- "X268: HAMBOL MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X269"] <- "X269: HAMBOL MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X270"] <- "X270: HAMBOL MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X271"] <- "X271: HAMBOL MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X272"] <- "X272: HAMBOL MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X273"] <- "X273: IFFOU MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X274"] <- "X274: IFFOU MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X275"] <- "X275: IFFOU MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X276"] <- "X276: IFFOU MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X277"] <- "X277: IFFOU MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X278"] <- "X278: IFFOU MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X279"] <- "X279: IFFOU MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X280"] <- "X280: IFFOU MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X281"] <- "X281: LA ME MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X282"] <- "X282: LA ME MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X283"] <- "X283: LA ME MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X284"] <- "X284: LA ME MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X285"] <- "X285: LA ME MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X286"] <- "X286: LA ME MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X287"] <- "X287: LA ME MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X288"] <- "X288: LA ME MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X289"] <- "X289: NAWA MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X290"] <- "X290: NAWA MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X291"] <- "X291: NAWA MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X292"] <- "X292: NAWA MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X293"] <- "X293: NAWA MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X294"] <- "X294: NAWA MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X295"] <- "X295: NAWA MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X296"] <- "X296: NAWA MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X297"] <- "X297: TCHOLOGO MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X298"] <- "X298: TCHOLOGO MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X299"] <- "X299: TCHOLOGO MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X300"] <- "X300: TCHOLOGO MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X301"] <- "X301: TCHOLOGO MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X302"] <- "X302: TCHOLOGO MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X303"] <- "X303: TCHOLOGO MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X304"] <- "X304: TCHOLOGO MILIEU 2 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X305"] <- "X305: MORONOU MILIEU 1 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X306"] <- "X306: MORONOU MILIEU 1 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X307"] <- "X307: MORONOU MILIEU 2 SEX 1 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X308"] <- "X308: MORONOU MILIEU 2 SEX 1 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X309"] <- "X309: MORONOU MILIEU 1 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X310"] <- "X310: MORONOU MILIEU 1 SEX 2 AGE 15_plus"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X311"] <- "X311: MORONOU MILIEU 2 SEX 2 AGE 0_14"
X_Summary_Table$X_Labels[X_Summary_Table$X_Constraints=="X312"] <- "X312: MORONOU MILIEU 2 SEX 2 AGE 15_plus"
